[account]
private_key = "0"
transaction_limit = 10
dry_run = true
simulate = false

[global]
mode = "Mint"
proxy_url = ""
provider_url = "https://eth.721.gg/"
flashbots_signer = ""
relays = [
    "https://relay.flashbots.net",
    "https://mev-relay.ethermine.org",
    "https://api.taichi.network:10001/rpc/public",
    "https://api.edennetwork.io/v1/bundle",
    "https://bundle.miningdao.io"
]

[mint]
contract_address = "0x8B003fBF5d089c23a87563E3b53450ca891D741D"
function = "mint(uint256)"
arguments = [{ type = "Uint", value = 3 }]
value = 0.07e18
gas_fee = 1000
priority_fee = 1000
gas_limit = 250_000
start_time = 0
multi_mint = false
multi_mint_max = 0

[opensea]
api = "GraphQL"
api_key = ""
smart_gas = "Exclusive"
estimate_gas = false
gas_fee = 1000
priority_fee = 1000
gas_limit = 250_000
maximum_retry_attempts = 10

[opensea.drop]
maximum_price = 0.0
token_id = ""
contract_address = ""
listing_username = ""
max_orders = 1

[opensea.limit]
mode = "Collection"
minimum_price = 0.0
maximum_price = 6.0
collection_slug = "mekaverse"
token_id = ""
contract_address = ""
